yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='post'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'group_posts'), namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:settings.LIMIT_POST]


class Meta:
    ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        blank=False,
        null=True,
        related_name='comments',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.text


class Follow (models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='uniq_follow'
            )
        ]

    def __str__(self):
        return self.user

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .forms import PostForm, CommentForm
from .helpers import pagin
from .models import Group, Post, User, Follow


POSTS_AMOUNT = 10


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('author').all()
    context = {
        'page_obj': pagin(request, posts, POSTS_AMOUNT),
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': pagin(request, posts, POSTS_AMOUNT),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = author.following.exists()
    context = {
        'author': author,
        'following': following,
        'page_obj': pagin(request, author.posts.all(), POSTS_AMOUNT),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_list = author.posts.all()
    form = CommentForm(request.POST or None)
    commentss = post.comments.all()
    context = {
        'post': post,
        'post_list': post_list,
        'author': author,
        'form': form,
        'commentss': commentss,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST,
                        files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/create_post.html', {'form': form})
    else:
        form = PostForm()
        return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    instance=post,
                    files=request.FILES or None)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'form': form,
        'post': post,
        'is_edit': is_edit
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    subs = request.user.follower.values('author')
    posts = Post.objects.filter(
        author__in=subs).select_related('author', 'group')
    context = {
        'page_obj': pagin(request, posts, POSTS_AMOUNT),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect("posts:follow_index")

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">
                {% load user_filters %}       
                {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}

                <form method="post" enctype="multipart/form-data"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}>
                  
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3"
                  aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                   {{ field|addclass:'form-control' }}
                   {% if field.help_text %}
                     <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                       {{ field.help_text|safe }}
                     </small>
                   {% endif %}
                 </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
</form>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Это главная страница проекта Yatube
{% endblock %}
{% include 'posts/includes/switcher.html' %}
{% block content %}
<div class="container py-5">
  <h1>Избранные авторы</h1>
  {% load cache %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
    {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description }}</p>
  {% for post in page_obj %}
    <p>
      {{ post.group }}
    </p>
    {% include 'includes/post.html' %}
    <a href="">все записи группы</a>
      {% if not forloop.last %}
        <hr>
      {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Это главная страница проекта Yatube
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% load cache %}
  {% cache 20 index_page %}
  {% for post in page_obj %}
    {% include 'includes/post.html' %}
    {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
    {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
{{ title }} {{ post.text|truncatechars:30}}
{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ group.title}}
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ author.posts.count }}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <article class="col-12 col-md-9">
          <p>
           {{ post.text }}
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
          {% endif %}
          {% include 'includes/comment.html' %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Последние обновления на сайте
{% endblock %}
{% block content %}
{% load thumbnail %}
    <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
          {% endif %}
        {% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          {% if post.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        </article>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
      </div>
{% endblock %}